<a href="https://colab.research.google.com/github/datadigger01/Datahandling/blob/main/Code_example/week04_missingdata_reshape.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### 1. pandas의 read_csv 함수를 이용하여 DataFrame 구조로 데이터 불러오기

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/데이터처리실무/Data/Agent_Attrition.csv')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2401 entries, 0 to 2400
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   AgentID           2401 non-null   int64
 1   Tgt_3YN           2401 non-null   int64
 2   Age_Grp           2401 non-null   object
 3   Gender            2401 non-null   int64
 4   Apply_CH          2401 non-null   object
 5   re_hire_freq_grp  2401 non-null   object
 6   Q2                2401 non-null   int64
 7   Q7                2401 non-null   int64
 8   Q8                2401 non-null   int64
 9   Q18               2401 non-null   int64
 10  Q22               2401 non-null   int64
 11  Q38               2401 non-null   int64
 12  rank_INDEX14      2373 non-null   float64
 13  rank_INDEX18      2373 non-null   float64
 14  rank_INDEX23      2373 non-null   float64
 15  rank_INDEX27      2373 non-null   float64
 16  rank_INDEX28      2373 non-null   float64
 17  rank_INDEX29      2373 non-null   float64
 18  rank_INDEX32      2373 non-null   float64
 19  rank_INDEX44      2373 non-null   float64
 20  rank_INDEX93      2373 non-null   float64
 21  rank_AVG_AMT_6M   2401 non-null   int64
dtypes: float64(9), int64(10), object(3)
memory usage: 412.8+ KB

,AgentID,Tgt_3YN,Age_Grp,Gender,Apply_CH,re_hire_freq_grp,Q2,Q7,Q8,Q18,...,rank_INDEX14,rank_INDEX18,rank_INDEX23,rank_INDEX27,rank_INDEX28,rank_INDEX29,rank_INDEX32,rank_INDEX44,rank_INDEX93,rank_AVG_AMT_6M
0,1,1,5060G,2,Vender,1,3,1,4,2,...,2.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,6
1,2,0,40G,1,MGM,1,4,1,7,1,...,3.0,0.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,7
2,3,0,40G,2,MGM,4~,3,2,3,2,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
3,4,0,40G,2,MGM,1,4,1,6,3,...,2.0,1.0,0.0,2.0,2.0,2.0,0.0,1.0,1.0,0
4,5,0,40G,2,MGM,1,2,2,5,2,...,1.0,1.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2396,2397,0,30G,2,MGM,0,2,2,4,2,...,3.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,7
2397,2398,0,5060G,1,MGM,0,3,2,4,2,...,3.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,5
2398,2399,0,5060G,2,MGM,0,3,2,5,2,...,1.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,4
2399,2400,0,5060G,2,MGM,0,1,1,3,3,...,0.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,5
2400,2401,0,30G,2,MGM,0,2,3,3,1,...,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,4

- AgentID는 식별정보이므로 index 컬럼으로 변환

In [ ]:
# prompt: AgentID를 index 컬럼으로 설정하는 코드를 제공해주세요

df = df.set_index('AgentID')
df.info()
df

<class 'pandas.core.frame.DataFrame'>
Index: 2401 entries, 1 to 2401
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tgt_3YN           2401 non-null   int64
 1   Age_Grp           2401 non-null   object
 2   Gender            2401 non-null   int64
 3   Apply_CH          2401 non-null   object
 4   re_hire_freq_grp  2401 non-null   object
 5   Q2                2401 non-null   int64
 6   Q7                2401 non-null   int64
 7   Q8                2401 non-null   int64
 8   Q18               2401 non-null   int64
 9   Q22               2401 non-null   int64
 10  Q38               2401 non-null   int64
 11  rank_INDEX14      2373 non-null   float64
 12  rank_INDEX18      2373 non-null   float64
 13  rank_INDEX23      2373 non-null   float64
 14  rank_INDEX27      2373 non-null   float64
 15  rank_INDEX28      2373 non-null   float64
 16  rank_INDEX29      2373 non-null   float64
 17  rank_INDEX32      2373 non-null   float64
 18  rank_INDEX44      2373 non-null   float64
 19  rank_INDEX93      2373 non-null   float64
 20  rank_AVG_AMT_6M   2401 non-null   int64
dtypes: float64(9), int64(9), object(3)
memory usage: 412.7+ KB

,Tgt_3YN,Age_Grp,Gender,Apply_CH,re_hire_freq_grp,Q2,Q7,Q8,Q18,Q22,...,rank_INDEX14,rank_INDEX18,rank_INDEX23,rank_INDEX27,rank_INDEX28,rank_INDEX29,rank_INDEX32,rank_INDEX44,rank_INDEX93,rank_AVG_AMT_6M
AgentID,,,,,,,,,,,,,,,,,,,,,
1,1,5060G,2,Vender,1,3,1,4,2,3,...,2.0,0.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,6
2,0,40G,1,MGM,1,4,1,7,1,3,...,3.0,0.0,1.0,1.0,1.0,0.0,2.0,2.0,3.0,7
3,0,40G,2,MGM,4~,3,2,3,2,4,...,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5
4,0,40G,2,MGM,1,4,1,6,3,6,...,2.0,1.0,0.0,2.0,2.0,2.0,0.0,1.0,1.0,0
5,0,40G,2,MGM,1,2,2,5,2,1,...,1.0,1.0,2.0,2.0,3.0,2.0,1.0,1.0,2.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2397,0,30G,2,MGM,0,2,2,4,2,1,...,3.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,7
2398,0,5060G,1,MGM,0,3,2,4,2,6,...,3.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,5
2399,0,5060G,2,MGM,0,3,2,5,2,6,...,1.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0,3.0,4
2400,0,5060G,2,MGM,0,1,1,3,3,1,...,0.0,3.0,3.0,3.0,2.0,3.0,3.0,3.0,3.0,5
2401,0,30G,2,MGM,0,2,3,3,1,6,...,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,1.0,4

- Missing(NaN:Not a Number) 값이 존재하는 행(레코드) 출력

In [ ]:
# prompt: NaN이 하나라도 존재하는 행을 보여주는 코드를 제공해주세요

rows_with_nan = df[df.isnull().any(axis=1)]
rows_with_nan

,Tgt_3YN,Age_Grp,Gender,Apply_CH,re_hire_freq_grp,Q2,Q7,Q8,Q18,Q22,...,rank_INDEX14,rank_INDEX18,rank_INDEX23,rank_INDEX27,rank_INDEX28,rank_INDEX29,rank_INDEX32,rank_INDEX44,rank_INDEX93,rank_AVG_AMT_6M
AgentID,,,,,,,,,,,,,,,,,,,,,
14,0,5060G,2,MGM,4~,2,3,3,3,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
94,1,40G,2,MGM,1,3,2,3,4,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
206,0,5060G,2,MGM,0,2,2,7,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
273,1,30G,2,MGM,0,1,2,7,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
350,1,5060G,2,MGM,0,3,3,4,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
375,0,5060G,2,MGM,0,4,3,5,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
415,0,5060G,2,MGM,3,3,2,3,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
472,0,40G,1,MGM,3,1,2,5,3,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
538,0,5060G,2,MGM,3,3,2,4,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
633,1,40G,2,MGM,3,3,1,7,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
683,1,5060G,2,MGM,1,3,1,5,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
735,0,5060G,2,MGM,1,3,2,5,1,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7
750,0,40G,2,MGM,3,1,2,5,2,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
877,0,30G,2,MGM,1,1,2,5,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
934,1,40G,2,Vender,1,3,1,6,2,3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
962,0,5060G,2,MGM,0,3,4,2,3,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
1169,0,40G,2,MGM,1,2,1,3,2,4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
1192,0,40G,2,MGM,0,1,3,4,2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
1196,0,40G,1,Vender,0,4,2,7,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1433,0,5060G,2,MGM,0,3,1,3,3,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
1451,0,30G,2,Vender,0,1,1,3,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
1634,0,5060G,2,MGM,0,2,2,4,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8
1807,0,5060G,2,MGM,0,3,1,7,3,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9
2163,0,5060G,2,MGM,1,3,3,5,1,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
2185,1,40G,2,MGM,1,4,1,6,2,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2211,0,30G,2,MGM,1,4,2,4,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
2280,0,40G,1,MGM,0,2,5,1,1,6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6
2356,0,30G,2,Vender,0,3,2,4,2,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2

### 2. 데이터확인 및 정제
  - 기술통계량 산출
  - Missing/Null 값 확인 및 처리

##### 2.1 모든 컬럼에 대한 기술통계량(descriptive statistics) 산출 및 확인

In [ ]:
df.describe()

,Tgt_3YN,Gender,Q2,Q7,Q8,Q18,Q22,Q38,rank_INDEX14,rank_INDEX18,rank_INDEX23,rank_INDEX27,rank_INDEX28,rank_INDEX29,rank_INDEX32,rank_INDEX44,rank_INDEX93,rank_AVG_AMT_6M
count,2401.000000,2401.000000,2401.000000,2401.000000,2401.000000,2401.000000,2401.000000,2401.000000,2373.000000,2373.000000,2373.000000,2373.000000,2373.000000,2373.000000,2373.000000,2373.000000,2373.000000,2401.000000
mean,0.243232,1.860058,2.645564,2.076218,4.462307,1.816327,3.392753,1.424823,1.543194,1.507375,1.500211,1.491361,1.500632,1.579857,1.444585,1.500211,1.578171,5.706372
std,0.429123,0.346999,1.033476,0.946716,1.434811,0.819553,2.178745,0.494419,0.970653,1.155148,1.118081,1.073024,1.117704,1.158610,1.212283,1.118081,1.113452,2.627102
min,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,2.000000,2.000000,1.000000,3.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000,1.000000,4.000000
50%,0.000000,2.000000,3.000000,2.000000,4.000000,2.000000,3.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,1.000000,2.000000,2.000000,6.000000
75%,0.000000,2.000000,3.000000,2.000000,5.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,2.000000,3.000000,8.000000
max,1.000000,2.000000,5.000000,5.000000,7.000000,4.000000,6.000000,2.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,9.000000

In [ ]:
df.columns

Index(['Tgt_3YN', 'Age_Grp', 'Gender', 'Apply_CH', 're_hire_freq_grp', 'Q2',
       'Q7', 'Q8', 'Q18', 'Q22', 'Q38', 'rank_INDEX14', 'rank_INDEX18',
       'rank_INDEX23', 'rank_INDEX27', 'rank_INDEX28', 'rank_INDEX29',
       'rank_INDEX32', 'rank_INDEX44', 'rank_INDEX93', 'rank_AVG_AMT_6M'],
      dtype='object')

##### 2.2 셀수 있는(countable) 변수 와 범주형 변수에 대해 value_counts(dropna=False) 함수를 이용하여 빈도수 체크(missing 값 포함)

In [ ]:
# prompt: value_counts() 함수를 이용하여 'Age_Grp', 'Gender', 'Apply_CH', 're_hire_freq_grp',  'Q2', 'Q7', 'Q8', 'Q18', 'Q22', 'Q38',  'rank_INDEX14', 'rank_INDEX18','rank_INDEX23', 'rank_INDEX27', 'rank_INDEX28', 'rank_INDEX29','rank_INDEX32', 'rank_INDEX44', 'rank_INDEX93', 'rank_AVG_AMT_6M'' 컬럼에 대해 결과를 산출할 수 있느 코드를 제공해주세요

for column in ['Age_Grp', 'Gender', 'Apply_CH', 're_hire_freq_grp', 'Q2', 'Q7', 'Q8', 'Q18', 'Q22', 'Q38', 'rank_INDEX14', 'rank_INDEX18', 'rank_INDEX23', 'rank_INDEX27', 'rank_INDEX28', 'rank_INDEX29', 'rank_INDEX32', 'rank_INDEX44', 'rank_INDEX93', 'rank_AVG_AMT_6M']:
  print(f"Value counts for {column}:")
  print(df[column].value_counts(dropna=False))
  print("\n")

In [ ]:
import matplotlib.pyplot as plt
import seaborn as sns

columns_to_plot = [
    'rank_INDEX14', 'rank_INDEX18', 'rank_INDEX23',
    'rank_INDEX27', 'rank_INDEX28', 'rank_INDEX29',
    'rank_INDEX32', 'rank_INDEX44', 'rank_INDEX93'
]

# Calculate number of rows and columns for the subplot grid
n_cols = 3
n_rows = (len(columns_to_plot) + n_cols - 1) // n_cols # Ceiling division

fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 5, n_rows * 4))
axes = axes.flatten() # Flatten the 2D array of axes for easy iteration

for i, col in enumerate(columns_to_plot):
    if i < len(axes): # Ensure we don't go out of bounds if there are more columns than subplots
        sns.countplot(x=col, data=df, ax=axes[i], palette='viridis', hue=col, legend=False)
        axes[i].set_title(f'Frequency of {col}')
        axes[i].set_xlabel(col)
        axes[i].set_ylabel('Count')

# Hide any unused subplots
for j in range(len(columns_to_plot), len(axes)):
    fig.delaxes(axes[j])

plt.tight_layout()
plt.show()

##### 2.3 실수타입으로 지정된 rank_INDEX? 컬럼값을 최빈값으로 대체

In [ ]:
columns_to_process = ['rank_INDEX14', 'rank_INDEX18', 'rank_INDEX23', 'rank_INDEX27', 'rank_INDEX28',
                      'rank_INDEX29', 'rank_INDEX32', 'rank_INDEX44', 'rank_INDEX93', 'rank_AVG_AMT_6M']

for column in columns_to_process:
  # 최빈값 찾기
  most_frequent_value = df[column].mode()[0]
  # NaN 값을 최빈값으로 대체하고 정수형으로 변환
  df[column] = df[column].fillna(most_frequent_value).astype(int)

# 결과 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2401 entries, 1 to 2401
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tgt_3YN           2401 non-null   int64
 1   Age_Grp           2401 non-null   object
 2   Gender            2401 non-null   int64
 3   Apply_CH          2401 non-null   object
 4   re_hire_freq_grp  2401 non-null   object
 5   Q2                2401 non-null   int64
 6   Q7                2401 non-null   int64
 7   Q8                2401 non-null   int64
 8   Q18               2401 non-null   int64
 9   Q22               2401 non-null   int64
 10  Q38               2401 non-null   int64
 11  rank_INDEX14      2401 non-null   int64
 12  rank_INDEX18      2401 non-null   int64
 13  rank_INDEX23      2401 non-null   int64
 14  rank_INDEX27      2401 non-null   int64
 15  rank_INDEX28      2401 non-null   int64
 16  rank_INDEX29      2401 non-null   int64
 17  rank_INDEX32      2401 non-null   int64
 18  rank_INDEX44      2401 non-null   int64
 19  rank_INDEX93      2401 non-null   int64
 20  rank_AVG_AMT_6M   2401 non-null   int64
dtypes: int64(18), object(3)
memory usage: 412.7+ KB

In [ ]:
# Gender 컬럼을 문자타입으로 변환
df['Gender'] = df['Gender'].astype(str)

df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2401 entries, 1 to 2401
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Tgt_3YN           2401 non-null   int64
 1   Age_Grp           2401 non-null   object
 2   Gender            2401 non-null   object
 3   Apply_CH          2401 non-null   object
 4   re_hire_freq_grp  2401 non-null   object
 5   Q2                2401 non-null   int64
 6   Q7                2401 non-null   int64
 7   Q8                2401 non-null   int64
 8   Q18               2401 non-null   int64
 9   Q22               2401 non-null   int64
 10  Q38               2401 non-null   int64
 11  rank_INDEX14      2401 non-null   int64
 12  rank_INDEX18      2401 non-null   int64
 13  rank_INDEX23      2401 non-null   int64
 14  rank_INDEX27      2401 non-null   int64
 15  rank_INDEX28      2401 non-null   int64
 16  rank_INDEX29      2401 non-null   int64
 17  rank_INDEX32      2401 non-null   int64
 18  rank_INDEX44      2401 non-null   int64
 19  rank_INDEX93      2401 non-null   int64
 20  rank_AVG_AMT_6M   2401 non-null   int64
dtypes: int64(17), object(4)
memory usage: 412.7+ KB

In [ ]:
# 변경된 데이터프레임 확인
print(df.isnull().sum())

Tgt_3YN             0
Age_Grp             0
Gender              0
Apply_CH            0
re_hire_freq_grp    0
Q2                  0
Q7                  0
Q8                  0
Q18                 0
Q22                 0
Q38                 0
rank_INDEX14        0
rank_INDEX18        0
rank_INDEX23        0
rank_INDEX27        0
rank_INDEX28        0
rank_INDEX29        0
rank_INDEX32        0
rank_INDEX44        0
rank_INDEX93        0
rank_AVG_AMT_6M     0
dtype: int64

### 2. 데이터결합
- wdi_data(World Bank Data)
- country_region
- iso3c 컬럼을 key값으로 결합하되 country_region 데이터셋을 기반으로 left join

In [ ]:
df_wdi=pd.read_csv('https://raw.githubusercontent.com/datadigger01/Datahandling/main/Data/wdi_data.csv')
print(df_wdi.info())
df_wdi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17626 entries, 0 to 17625
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   country            17626 non-null  object
 1   iso2c              6095 non-null   object
 2   iso3c              6003 non-null   object
 3   year               17626 non-null  int64
 4   status             0 non-null      float64
 5   lastupdated        17626 non-null  object
 6   GDP_PER_CAPITA     5876 non-null   float64
 7   TOT_GDP_EX_OILGAS  7000 non-null   float64
 8   TOT_GDP_IN_OILGAS  7033 non-null   float64
 9   GDP_GROWTH_RATE    5805 non-null   float64
 10  NY.GDP.PCAP.KD.ZG  5802 non-null   float64
 11  TRADE_IN_GDP       5016 non-null   float64
 12  POPULATION         6095 non-null   float64
 13  EXPORT_LCU         3585 non-null   float64
 14  EXPORT_USD         5081 non-null   float64
 15  IMPORT_LCU         3585 non-null   float64
 16  IMPORT_USD         5129 non-null   float64
 17  region             5911 non-null   object
 18  capital            4807 non-null   object
 19  longitude          4807 non-null   float64
 20  latitude           4807 non-null   float64
 21  income             5911 non-null   object
 22  lending            5911 non-null   object
dtypes: float64(14), int64(1), object(8)
memory usage: 3.1+ MB
None

,country,iso2c,iso3c,year,status,lastupdated,GDP_PER_CAPITA,TOT_GDP_EX_OILGAS,TOT_GDP_IN_OILGAS,GDP_GROWTH_RATE,...,EXPORT_LCU,EXPORT_USD,IMPORT_LCU,IMPORT_USD,region,capital,longitude,latitude,income,lending
0,"Aceh Barat Daya, Kab.",NaN,NaN,2000,NaN,2022-08-11,NaN,474630.42,474630.42,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"Aceh Barat Daya, Kab.",NaN,NaN,2001,NaN,2022-08-11,NaN,482377.06,482377.06,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Aceh Barat Daya, Kab.",NaN,NaN,2002,NaN,2022-08-11,NaN,490292.82,490292.82,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,"Aceh Barat Daya, Kab.",NaN,NaN,2003,NaN,2022-08-11,NaN,500278.52,500278.52,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,"Aceh Barat Daya, Kab.",NaN,NaN,2004,NaN,2022-08-11,NaN,515314.74,515314.74,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17621,Zimbabwe,ZW,ZWE,2018,NaN,2024-02-21,2269.177012,NaN,NaN,5.009867,...,5.133275e+10,8.936585e+09,5.531567e+10,9.695644e+09,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,Blend
17622,Zimbabwe,ZW,ZWE,2019,NaN,2024-02-21,1421.868596,NaN,NaN,-6.332446,...,5.846286e+10,6.015688e+09,5.992188e+10,6.165817e+09,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,Blend
17623,Zimbabwe,ZW,ZWE,2020,NaN,2024-02-21,1372.696674,NaN,NaN,-7.816951,...,2.984573e+10,4.795171e+09,3.349693e+10,5.381792e+09,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,Blend
17624,Zimbabwe,ZW,ZWE,2021,NaN,2024-02-21,1773.920411,NaN,NaN,8.468017,...,4.388753e+10,6.461618e+09,5.409408e+10,7.964342e+09,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,Blend
17625,Zimbabwe,ZW,ZWE,2022,NaN,2024-02-21,1676.821489,NaN,NaN,6.522375,...,6.317568e+10,7.650408e+09,8.361894e+10,1.012603e+10,Sub-Saharan Africa,Harare,31.0672,-17.8312,Lower middle income,Blend

In [ ]:
df_country=pd.read_csv('https://raw.githubusercontent.com/datadigger01/Datahandling/main/Data/country_region.csv')
print(df_country.info())
df_country

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   name                      249 non-null    object
 1   iso2c                     248 non-null    object
 2   iso3c                     249 non-null    object
 3   country-code              249 non-null    int64
 4   iso_3166-2                249 non-null    object
 5   region                    247 non-null    object
 6   sub_region                247 non-null    object
 7   intermediate_region       105 non-null    object
 8   region_code               247 non-null    float64
 9   sub_region_code           247 non-null    float64
 10  intermediate_region_code  105 non-null    float64
dtypes: float64(3), int64(1), object(7)
memory usage: 21.5+ KB
None

,name,iso2c,iso3c,country-code,iso_3166-2,region,sub_region,intermediate_region,region_code,sub_region_code,intermediate_region_code
0,Afghanistan,AF,AFG,4,ISO 3166-2:AF,Asia,Southern Asia,NaN,142.0,34.0,NaN
1,Islands,AX,ALA,248,ISO 3166-2:AX,Europe,Northern Europe,NaN,150.0,154.0,NaN
2,Albania,AL,ALB,8,ISO 3166-2:AL,Europe,Southern Europe,NaN,150.0,39.0,NaN
3,Algeria,DZ,DZA,12,ISO 3166-2:DZ,Africa,Northern Africa,NaN,2.0,15.0,NaN
4,American Samoa,AS,ASM,16,ISO 3166-2:AS,Oceania,Polynesia,NaN,9.0,61.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...
244,Wallis and Futuna,WF,WLF,876,ISO 3166-2:WF,Oceania,Polynesia,NaN,9.0,61.0,NaN
245,Western Sahara,EH,ESH,732,ISO 3166-2:EH,Africa,Northern Africa,NaN,2.0,15.0,NaN
246,Yemen,YE,YEM,887,ISO 3166-2:YE,Asia,Western Asia,NaN,142.0,145.0,NaN
247,Zambia,ZM,ZMB,894,ISO 3166-2:ZM,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0
248,Zimbabwe,ZW,ZWE,716,ISO 3166-2:ZW,Africa,Sub-Saharan Africa,Eastern Africa,2.0,202.0,14.0

- 2개의 데이터셋을 iso3c컬럼(key) 기준으로 df_country 데이터셋기준 left join
- df_country 데이터셋의 region, region_code, sub_region, sub_region_code 컬럼만 선택이 되도록

- "GDP_PER_CAPITA", "GDP_GROWTH_RATE" 컬럼에 대해서 보간법으로 결측치 대체

#### 3. 데이터구조변환(Reshape)
- GDP_GROWTH_RATE 관련 컬럼을 대상으로 long -> wide